import Head from 'next/head';
import { Inter } from 'next/font/google';
import { HomePage } from '@/components/home/home-page';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ data }) {
   return (
      <>
         <Head>
            <title>Events App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <HomePage data={data} />
      </>
   );
}

// Phải được tách biệt với UI
export async function getServerSideProps() {
   // Dùng với file .json
   const { events_categories } = await import('/data/data.json');
   // Dùng với REST API
   //  const res = await fetch('URL');
   //  const data = res.json();
   return {
      props: {
         data: events_categories,
      },
   };
}
